[build]
  publish = "."
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[build.environment]
  NODE_VERSION = "18"

#cant find a sliver bullet for the display problem let's just redirect the waiver page out to google form alone
#i put a link to jump back after submission
#another note: i bypassed the captcha using brevo, 300 emails per day should be enough
# URL aliases for cleaner URLs
[[redirects]]
  from = "/waiver"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSf_MCkZ95evnMw7oDOgIHocWRAnmq0vNKyPIJMu4tkpy5WxHA/viewform?usp=header"
  #to = "/pages/waiver.html"
  status = 301 

[[redirects]]
  from = "/waiver"
  to = "https://docs.google.com/forms/d/e/1FAIpQLSf_MCkZ95evnMw7oDOgIHocWRAnmq0vNKyPIJMu4tkpy5WxHA/viewform?usp=header"
  status = 301 

# Main redirect for single-page app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


